baseURL = '/'
languageCode = 'fa-ir'
title = "AmirSadra's Blog"  # <--- تصحیح شده: استفاده از علامت نقل قول دوتایی و مالکیت صحیح
theme = "PaperMod"

[params]
rtl = true

[imaging] #baraye nashan dadan aks
quality = 90
resampleFilter = "Lanczos"
